### ISSUE TITLE
error image loading on Linux

### ISSUE THREAD

**Issue by skazimax** [Microsoft/VoTT#164]
Hi, i installed VOTT on Ubuntu with npm install, but when i try to load image dir, it's stays on a tag selection page, continue button not working.
I enabled debug and see this errors:

Uncaught Error: Cannot find module 'cntk-fastrcnn'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/mnt/Data/GIT/VoTT/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/Data/GIT/VoTT/src/lib/detection_algorithms/cntkfastrcnn/reviewer.js:5:18)
    at Object.<anonymous> (/mnt/Data/GIT/VoTT/src/lib/detection_algorithms/cntkfastrcnn/reviewer.js:74:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
index.js:227 Error loading save file Cannot find module '/mnt/Data/HIK/Out/A.json'
index.js:314 Uncaught ReferenceError: DetectionExtension is not defined
    at HTMLDivElement.loadTagger (index.js:314)
loadTagger @ index.js:314

**Comment by aribornstein** [comment]
Hmm that is strange the cntk-fastrcnn module shouldn't affect loading an image directory. Did you accidentally run the reviewer? That feature doesn't yet work in linux. I'll take a further look tomorrow to see if i can reproduce the error and will update you with my findings.

Best of luck,
-Ari

**Comment by skazimax** [comment]
Hi, i run it as npm start

**Comment by aribornstein** [comment]
found the bug will fix shortly

**Comment by aribornstein** [comment]
This should now be resolved once you confirm i will close this issue. Thanks for bringing this to my attention

**Comment by skazimax** [comment]
Thanks, yes it's working now
