### ISSUE TITLE
Unknown UI Test Error (Jest & Enzyme)

### ISSUE THREAD

**Issue by JordanEllis6809** [Microsoft/VoTT#407]
It looks as though the culprit is the `SAVE_CONNECTION_SUCCESS` action, and sparks a chain of errors? Repro steps down below. 

```
 RUNS  src/react/components/pages/connections/**connectionsPage.test.tsx**

Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
  console.group node_modules/redux-logger/dist/redux-logger.js:1
       action SAVE_CONNECTION_SUCCESS @ 16:22:38.575

  console.log node_modules/redux-logger/dist/redux-logger.js:1
    prev state { appSettings: null,
      connections: [],
      recentProjects: [],
      currentProject: null }

  console.log node_modules/redux-logger/dist/redux-logger.js:1
      action { type: 'SAVE_CONNECTION_SUCCESS',
      payload:
       { name: 'test',
         description: undefined,
         providerType: 'azureBlobStorage',
         providerOptions:
          { accountName: undefined,
            accountKey: undefined,
            connectionString: 'test',
            containerName: 'test',
            createContainer: undefined },
         id: 'yYGm5Y5Br' } }

  console.log node_modules/redux-logger/dist/redux-logger.js:1
    next state
      connections:
       [ { name: 'test',
           description: undefined,
           providerType: 'azureBlobStorage',
           providerOptions: [Object],
           id: 'yYGm5Y5Br' } ],
      recentProjects: [],
      currentProject: null }

/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:62
    throw error;
    ^

Invariant Violation: The `document` global was defined when React was initialized, but is not defined anymore. This can happen in a test environment if a component schedules an update from an asynchronous callback, but the test has already finished running. To solve this, you can either unmount the component at the end of your test (and ensure that any asynchronous operations get canceled in `componentWillUnmount`), or you can change the test itself to be asynchronous.
    at invariant (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:55:15)
    at Object.invokeGuardedCallbackDev (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:110:44)
    at invokeGuardedCallback (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:256:31)
    at commitRoot (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:17391:7)
    at completeRoot (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18912:3)
    at performWorkOnRoot (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18841:9)
    at performWork (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18749:7)
    at performSyncWork (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18723:3)
    at requestWork (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18592:5)
    at scheduleWork (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:18401:5)
    at Object.enqueueSetState (/home/Dev/Repos/VoTT/node_modules/react-dom/cjs/react-dom.development.js:12313:5)
    at ConnectionForm.Object.<anonymous>.Component.setState (/home/Dev/Repos/VoTT/node_modules/react/cjs/react.development.js:372:16)
```

To reproduce, pull branch `joelli/v2/connection-page-tests`, install deps, and run `npm run test`.

Looking into this now...

**Comment by JordanEllis6809** [comment]
The error is still taking place when the props.actions.saveConnection method is being stubbed out, not sure how this could be.

Commit: https://github.com/Microsoft/VoTT/commit/5459406e32c3c0ab9ff57447324f9002adc75239
