### ISSUE TITLE
Error using `npm` to install on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by tauhlim** [microsoft/VoTT#967]
**Describe the bug**
Unable to install using NPM by following the instructions in the readme.

I get the following output in the console:
```
> fsevents@1.2.4 install /home/tauherng/VoTT/node_modules/fsevents
> node install


> node-sass@4.11.0 install /home/tauherng/VoTT/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

...

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/VoTT/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-1020-azure
gyp ERR! command "/usr/bin/node" "/home/user/VoTT/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/user/VoTT/node_modules/node-sass
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-05-27T02_56_27_399Z-debug.log
```

**To Reproduce**
```
 git clone https://github.com/Microsoft/VoTT.git
 cd VoTT
 npm ci
```

**Expected behavior**
Install.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS

**Comment by tauhlim** [comment]
Downgrading to Node 10.x worked. 

Was previously on Node 13.x
