### ISSUE TITLE
Unexepected Token ELIFECYCLE npm syntax error when running npm ci on VoTT to correctely identify cause and fix(correct)

### ISSUE THREAD

**Issue by goodengineer** [microsoft/VoTT#976]
Hello.

Does anyone know and can help/clarify to fix next when running npm ci:

...
> node-sass@4.11.0 postinstall D:\VOTT\VoTT\node_modules\node-sass
> node scripts/build.js

Binary found at D:\VOTT\VoTT\node_modules\node-sass\vendor\win32-x64-59\binding.node
Testing binary
Binary is fine

> ejs@3.1.2 postinstall D:\VOTT\VoTT\node_modules\ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> electron@3.0.13 postinstall D:\VOTT\VoTT\node_modules\electron
> node install.js

> vott@2.2.0 postinstall D:\VOTT\VoTT
> electron-builder install-app-deps

D:\VOTT\VoTT\node_modules\electron-builder\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\VOTT\VoTT\node_modules\electron-builder\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vott@2.2.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vott@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-06-16T07_54_58_395Z-debug.log

?

Kind Regards,
Paul.
![Screenshot (1659)](https://user-images.githubusercontent.com/60963077/84749404-9b2aa180-afc2-11ea-8da4-11c831d2832a.png)
![Screenshot (1660)](https://user-images.githubusercontent.com/60963077/84749408-9c5bce80-afc2-11ea-8450-547e7aa8900c.png)

**Comment by series8217** [comment]
Make sure you are using node 10.x

https://nodejs.org/dist/latest-v10.x/

**Comment by goodengineer** [comment]
Trying to resolve it:

Why next?:

D:\VOTT\Latest\rel01July2020\VoTT>node -v
v10.21.0

D:\VOTT\Latest\rel01July2020\VoTT>npm -v
6.14.5

D:\VOTT\Latest\rel01July2020\VoTT>npm ci
npm WARN prepare removing existing node_modules/ before installation
npm WARN tarball tarball data for app-builder-bin@3.5.8 (sha512-ni3q7QTfQNWHNWuyn5x3FZu6GnQZv+TFnfgk5++svqleKEhHGqS1mIaKsh7x5pBX6NFXU3/+ktk98wA/AW4EXw==) seems to be corrupted. Trying one more time.
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path D:\VOTT\Latest\rel01July2020\VoTT\node_modules\app-builder-bin\linux\arm64\app-builder
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\VOTT\Latest\rel01July2020\VoTT\node_modules\app-builder-bin\linux\arm64\app-builder'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\VOTT\Latest\rel01July2020\VoTT\node_modules\app-builder-bin\linux\arm64\app-builder']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\VOTT\Latest\rel01July2020\VoTT\node_modules\app-builder-bin\linux\arm64\app-builder'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'D:\\VOTT\\Latest\\rel01July2020\\VoTT\\node_modules\\app-builder-bin\\linux\\arm64\\app-builder' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'D:\\VOTT\\Latest\\rel01July2020\\VoTT\\node_modules\\app-builder-bin\\linux\\arm64\\app-builder\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'D:\\VOTT\\Latest\\rel01July2020\\VoTT\\node_modules\\app-builder-bin\\linux\\arm64\\app-builder' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-07-03T07_49_58_247Z-debug.log

?

**Comment by shubh10482** [comment]
Getting similar issue as @goodengineer 

**NOTE:** I am using  node version as 10.22.0 and which is using 6.14.6 version of npm.

Below are the steps to regenerate the issue:
1. Git clone
2. npm ci

Getting below error:


$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm WARN tarball tarball data for @fortawesome/fontawesome-free@5.6.1 (sha1-6wlqSURtZJvcjJDwRAAwbv98M8I=) seems to be corrupted. Trying
one more time.
npm WARN tarball tarball data for reactstrap@6.5.0 (sha512-dWb3fB/wBAiQloteKlf+j9Nl2VLe6BMZgTEt6hpeTt0t9TwtkeU+2v2NBYONZaF4FZATfMiIKozhWpc2HmLW1g==) seems to be corrupted. Trying one more time.
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path D:\Personal Projects\VoTT\node_modules\reactstrap\dist\reactstrap.full.js.map
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\Personal Projects\VoTT\node_modules\reactstrap\dist\reactstrap.full.js.map'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\Personal Projects\VoTT\node_modules\reactstrap\dist\reactstrap.full.js.map']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\Personal Projects\VoTT\node_modules\reactstrap\dist\reactstrap.full.js.map'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'D:\\Personal Projects\\VoTT\\node_modules\\reactstrap\\dist\\reactstrap.full.js.map' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'D:\\Personal Projects\\VoTT\\node_modules\\reactstrap\\dist\\reactstrap.full.js.map\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'D:\\Personal Projects\\VoTT\\node_modules\\reactstrap\\dist\\reactstrap.full.js.map' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm WARN tarball tarball data for typescript@3.2.2 (sha1-/oEBxGqhI/g1NSPr3PVzDCrkk+U=) seems to be corrupted. Trying one more time.



![VoTTError](https://user-images.githubusercontent.com/65259531/89604589-359fb680-d889-11ea-9434-428363b5a891.PNG)

**Comment by MimirRnD** [comment]
Getting the same issue too.
